### ISSUE TITLE
Doesn't build with LTS-11.4

### ISSUE THREAD

**Issue by int-index** [markus1189/hoggl#7]
```
Progress 20/21               
--  While building custom Setup.hs for package hoggl-0.2.0.0 using:
      /home/int-index/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/int-index/Projects/yt-utilities/.stack-work/logs/hoggl-0.2.0.0.log

    Configuring hoggl-0.2.0.0...
    Preprocessing library for hoggl-0.2.0.0..
    Building library for hoggl-0.2.0.0..
    [1 of 3] Compiling Network.Hoggl.Types ( src/Network/Hoggl/Types.hs, .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/Network/Hoggl/Types.o )
    [2 of 3] Compiling Network.Hoggl.Pretty ( src/Network/Hoggl/Pretty.hs, .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/Network/Hoggl/Pretty.o )
    [3 of 3] Compiling Network.Hoggl    ( src/Network/Hoggl.hs, .stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/Network/Hoggl.o )
    
    /run/user/1000/stack8175/hoggl-0.2.0.0/src/Network/Hoggl.hs:59:28: error:
        * Constructor `DecodeFailure' does not have field `responseBody'
        * In the pattern: DecodeFailure {responseBody = "{\"data\":null}"}
          In an equation for `handler':
              handler DecodeFailure {responseBody = "{\"data\":null}"}
                = return Nothing
          In an equation for `currentTimeEntry':
              currentTimeEntry token
                = (Just <$> currentTimeEntry' (Just token)) `catchError` handler
                where
                    handler :: ServantError -> ClientM (Maybe TimeEntry)
                    handler DecodeFailure {responseBody = "{\"data\":null}"}
                      = return Nothing
                    handler e = throwError e
       |
    59 |     handler DecodeFailure {responseBody = "{\"data\":null}"} = return Nothing
       |                            ^^^^^^^^^^^^
    
    /run/user/1000/stack8175/hoggl-0.2.0.0/src/Network/Hoggl.hs:131:59: error:
        * Couldn't match expected type `ClientEnv'
                      with actual type `Maybe
                                          (GHC.Conc.Sync.TVar
                                             http-client-0.5.12:Network.HTTP.Client.Types.CookieJar)
                                        -> ClientEnv'
        * Probable cause: `ClientEnv' is applied to too few arguments
          In the second argument of `($)', namely
            `ClientEnv manager togglBaseUrl'
          In a stmt of a 'do' block:
            etimer <- runClientM (currentTimeEntry authorization)
                        $ ClientEnv manager togglBaseUrl
          In the expression:
            do manager <- newManager tlsManagerSettings
               etimer <- runClientM (currentTimeEntry authorization)
                           $ ClientEnv manager togglBaseUrl
               case etimer of
                 Right (Just timer) -> calcDuration timer >>= T.putStrLn . pretty
                 _ -> return ()
        |
    131 |   etimer <- runClientM (currentTimeEntry authorization) $ ClientEnv manager togglBaseUrl
        |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    /run/user/1000/stack8175/hoggl-0.2.0.0/src/Network/Hoggl.hs:140:63: error:
        * Couldn't match expected type `ClientEnv'
                      with actual type `Maybe
                                          (GHC.Conc.Sync.TVar
                                             http-client-0.5.12:Network.HTTP.Client.Types.CookieJar)
                                        -> ClientEnv'
        * Probable cause: `clientEnv' is applied to too few arguments
          In the second argument of `runClientM', namely `clientEnv'
          In a stmt of a 'do' block:
            currentTimer <- runClientM
                              (currentTimeEntry authorization) clientEnv
          In the expression:
            do manager <- newManager tlsManagerSettings
               let clientEnv = ClientEnv manager togglBaseUrl
               currentTimer <- runClientM
                                 (currentTimeEntry authorization) clientEnv
               case currentTimer of
                 Right Nothing
                   -> first ServantError
                        <$>
                          runClientM (startTimer authorization defaultTimeEntry) clientEnv
                 Right (Just _)
                   -> return (Left (HogglError "There already is a running timer!"))
                 Left e -> return (Left (ServantError e))
        |
    140 |   currentTimer <- runClientM (currentTimeEntry authorization) clientEnv
        |                                                               ^^^^^^^^^
    
    /run/user/1000/stack8175/hoggl-0.2.0.0/src/Network/Hoggl.hs:143:85: error:
        * Couldn't match expected type `ClientEnv'
                      with actual type `Maybe
                                          (GHC.Conc.Sync.TVar
                                             http-client-0.5.12:Network.HTTP.Client.Types.CookieJar)
                                        -> ClientEnv'
        * Probable cause: `clientEnv' is applied to too few arguments
          In the second argument of `runClientM', namely `clientEnv'
          In the second argument of `(<$>)', namely
            `runClientM (startTimer authorization defaultTimeEntry) clientEnv'
          In the expression:
            first ServantError
              <$>
                runClientM (startTimer authorization defaultTimeEntry) clientEnv
        |
    143 |       first ServantError <$> runClientM (startTimer authorization defaultTimeEntry) clientEnv
        |                                                                                     ^^^^^^^^^
    
    /run/user/1000/stack8175/hoggl-0.2.0.0/src/Network/Hoggl.hs:151:63: error:
        * Couldn't match expected type `ClientEnv'
                      with actual type `Maybe
                                          (GHC.Conc.Sync.TVar
                                             http-client-0.5.12:Network.HTTP.Client.Types.CookieJar)
                                        -> ClientEnv'
        * Probable cause: `clientEnv' is applied to too few arguments
          In the second argument of `runClientM', namely `clientEnv'
          In a stmt of a 'do' block:
            currentTimer <- runClientM
                              (currentTimeEntry authorization) clientEnv
          In the expression:
            do manager <- newManager tlsManagerSettings
               let clientEnv = ClientEnv manager togglBaseUrl
               currentTimer <- runClientM
                                 (currentTimeEntry authorization) clientEnv
               case currentTimer of
                 Right (Just TimeEntry {teId = tid})
                   -> first ServantError
                        <$> runClientM (stopTimer authorization tid) clientEnv
                 Right Nothing -> return (Left (HogglError "No timer running!"))
                 Left e -> return (Left (ServantError e))
        |
    151 |   currentTimer <- runClientM (currentTimeEntry authorization) clientEnv
        |                                                               ^^^^^^^^^
    
    /run/user/1000/stack8175/hoggl-0.2.0.0/src/Network/Hoggl.hs:154:71: error:
        * Couldn't match expected type `ClientEnv'
                      with actual type `Maybe
                                          (GHC.Conc.Sync.TVar
                                             http-client-0.5.12:Network.HTTP.Client.Types.CookieJar)
                                        -> ClientEnv'
        * Probable cause: `clientEnv' is applied to too few arguments
          In the second argument of `runClientM', namely `clientEnv'
          In the second argument of `(<$>)', namely
            `runClientM (stopTimer authorization tid) clientEnv'
          In the expression:
            first ServantError
              <$> runClientM (stopTimer authorization tid) clientEnv
        |
    154 |       first ServantError <$> runClientM (stopTimer authorization tid) clientEnv
        |                                                                       ^^^^^^^^^
```

**Comment by markus1189** [comment]
Closing this because pr is merged
